---
sync_users_from_bambo_api:
  cron: "0 6 * * *"
  class: SyncUsersJob
  queue: users
  description: "This job will sync the users from bamboo API every day at 6am"

mail_bonus_engine_active_events:
  cron: "0 7 * * *"
  class: MailActiveEventsJob
  queue: default
  description: "Sends an email to active event users that has positive balance"

# * * * * *  command to execute
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ └───── day of week (0 - 6) (0 to 6 are Sunday to Saturday, or use names; 7 is Sunday, the same as 0)
# │ │ │ └────────── month (1 - 12)
# │ │ └─────────────── day of month (1 - 31)
# │ └──────────────────── hour (0 - 23)
# └───────────────────────── min (0 - 59)
